Backend/web api/controllers
Nafanyan/WebCalendar pull request #10
Opened 2023-05-25 07:41 UTC by Nafanyan

2023-05-25 08:03 UTC, SherlockD requested changes

2023-05-25 08:03 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +            GetUserByIdDto getUserByIdDto = new GetUserByIdDto
Почему бы нам не создавать тут квери сразу? Тут лишний совершенно объект

2023-05-25 08:03 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +            QueryResult<User> queryResult = await _getUserByIdQueryHandler.HandleAsync(getUserByIdDto.Map());
А где проверка что валидация прошла или не прошла? Думаю стоит не Ok() возвращать, а BadRequest если валидация не прошла)

2023-05-25 08:03 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +        [HttpGet("{id}")]
userId

2023-05-25 08:03 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +            CommandResult commandResult = await _createUserCommandHandler.HandleAsync(createUserDto.Map());
Вот тут да, согласен что мапить нужно

2023-05-25 08:03 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +        public async Task<IActionResult> PutLogin([FromBody] UpdateUserLoginDto updateUserLoginDto)
Update login

2023-05-25 08:03 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +        public async Task<IActionResult> PutLogin([FromBody] UpdateUserLoginDto updateUserLoginDto)
не знаю конечно где пригодится этот метод, вроде как ни в одном сервисе логин нельзя поменять)

2023-05-25 08:03 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Mappers/UserMappers/CreateUserCommandMapper.cs
> +        public static CreateUserCommand Map(this CreateUserDto createUserDto)
молодец что использовал расширения, правильное решение

2023-05-25 08:05 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +        [HttpGet("{id}")]
хотяя, в целом и так понятно, давай оставим

2023-05-25 08:39 UTC, SherlockD requested changes

2023-05-25 08:39 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +                return BadRequest(queryResult.ValidationResult.Error);
тут можно также query result возвращать

2023-05-25 08:39 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +        public async Task<IActionResult> PutPassword([FromBody] UpdateUserPasswordDto updateUserPasswordDto)
UpdatePassword, ты ведь при post запросе не пишешь PostCreateUser) это не правильное решение

2023-05-26 07:42 UTC, SherlockD requested changes

2023-05-26 07:42 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/EventsController.cs
> +    [Route("Users")]
Почему Users

2023-05-26 07:42 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/EventsController.cs
> +        [HttpGet("{userId}/[controller]/{startEvent}/{endEvent}")]
startEvent, endEvent как будто бы гет параметрыми нужно сделать, не понятно из пути что там за поля

2023-05-26 07:42 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/EventsController.cs
> +    [Route("Users")]
А, я понял, так то да, норм, мы же через юзера туда обращаемся.

2023-05-26 07:42 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/EventsController.cs
> +        public async Task<IActionResult> CreateEvent([FromBody] CreateEventDto createEventDto)
Предлагаю переименовать Dto->Request

2023-05-26 07:42 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/EventsController.cs
> +            CommandResult commandResult = await _createEventCommandHandler.HandleAsync(createEventDto.Map());
у тебя в роуте уже есть userId, но ты нигде не исопльзуешь его, подумай как можно сделать

2023-05-26 12:04 UTC, SherlockD requested changes

2023-05-26 12:04 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +        public async Task<IActionResult> UpdateLogin([FromBody] UpdateUserLoginDto updateUserLoginDto)
А мы эти два метода не можем одним написать?) Типа UpdateUser(UserDto) и обновлять)

2023-05-26 13:41 UTC, SherlockD requested changes

2023-05-26 13:41 UTC, SherlockD commented on Application/Events/Commands/CreateEvent/CreateEventCommandValidation.cs
> +            DateTime.TryParse(command.StartEvent, out startEvent);
подумай как исправить

2023-05-26 13:59 UTC, Nafanyan commented on Web/Presentation.Intranet.Api/Controllers/UsersController.cs
> +        public async Task<IActionResult> UpdateLogin([FromBody] UpdateUserLoginDto updateUserLoginDto)
ну не, давай оставим так)

Чтобы обновить пароль нужно ввести старый и новый;
Чтобы обновить логин нужно ввести новый логин и действующий пароль.

2023-05-26 17:26 UTC, merged