Creating authorization
Nafanyan/WebCalendar pull request #19
Opened 2023-07-10 12:48 UTC by Nafanyan

2023-07-11 07:58 UTC, SherlockD requested changes

2023-07-11 07:58 UTC, SherlockD commented on Domain/Repositories/IUserAuthorizationRepository.cs
> +    public interface IUserAuthorizationRepository : IAddedRepository<UserAuthorizationToken>
UserAuthorizationTokenRepository

2023-07-11 07:58 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/AuthenticateController.cs
> +        public async Task<IActionResult> CheckToken()
await где

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +        private JwtSecurityToken CreateToken(List<Claim> authClaims)
100 процентов не тут должно быть, какая то другая сущность должна управлять. По принципу единственной ответственности, его тоже прочитай

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +        private string GenerateRefreshToken()
Это тоже

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryValidator.cs
> +                return ValidationResult.Fail("There is no user with this username");
Такую ошибку возвращать небезопасно, иначе можно через форму логинации перебирать логины, обычно пишут просто неверное имя пользователя или парль

2023-07-11 07:58 UTC, SherlockD commented on Domain/Entities/UserAuthorizationToken.cs
> +        public string RefreshToken { get; private set; }
А время жизни токена где хранится? Или это в конфиге будет?

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +            List<Claim> authClaims = new List<Claim>
Может сначала провалидировать query, а потом логику какую то?

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +                await _unitOfWork.CommitAsync();
Прикольно конечно, что в query должно находится? А что не должно?

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQuery.cs
> +    public class AuthorizationUserQuery
![image](https://github.com/Nafanyan/WebCalendar/assets/27965916/ae947d2c-4bbd-4fe0-80a8-679ee406508e)

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +            if (!validationResult.IsFail)
if isFail {

}

///твой код

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +                    await _userAuthorizationRepository.AddAsync(new UserAuthorizationToken(newRefreshToken, query.UserId));
Вроде асинковый Add в DbSet используется только если используется алгоритм HiLo

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +        private int _tokenValidityInMinutes = 15;
вот такое все лучше в конфиг засунуть

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +        private int _refreshTokenValidityInDays = 15;
И такое

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +        private string _secret = "MyVerySecretKey41 25345 4647 sd afs fdsg s agf";
Секрет хранить в хендлере, хз

2023-07-11 07:58 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +        private string _secret = "MyVerySecretKey41 25345 4647 sd afs fdsg s agf";
В конфиг можно засунуть, но знай, что это не безопасно, если получат доступ либо к репозиторию либо к виртуалке - пиши пропало

2023-07-11 10:18 UTC, Nafanyan commented on Application/UserAuthorizationTokens/AuthorizationUserQuery.cs
> +    public class AuthorizationUserQuery
![image](https://github.com/Nafanyan/WebCalendar/assets/90004716/81cf9017-2d9e-46b1-a91c-ceab19a8db13)

2023-07-11 10:18 UTC, Nafanyan commented on Application/UserAuthorizationTokens/AuthorizationUserQuery.cs
> +    public class AuthorizationUserQuery
Яндекс подстава(((

2023-07-11 10:20 UTC, Nafanyan commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +                    await _userAuthorizationRepository.AddAsync(new UserAuthorizationToken(newRefreshToken, query.UserId));
Ну мы с тобой изначально обусловились, что все методы, которые направлены на работу с  должны быть БД асинхронными)

2023-07-11 10:51 UTC, SherlockD requested changes

2023-07-11 10:51 UTC, SherlockD commented on Application/UserAuthorizationTokens/AuthorizationUserQueryHandler.cs
> +                    await _userAuthorizationRepository.AddAsync(new UserAuthorizationToken(newRefreshToken, query.UserId));
Но тебе на предзащите сказали, что не нужно его тут использовать) Если не имеет смысла то зачем)

2023-07-13 06:53 UTC, SherlockD requested changes

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/CreateToken/TokenCreateCommandHandler.cs
> +            if (!validationResult.IsFail)
if ( validationResult.IsFail )
{
return 
}

//Code

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/CreateToken/TokenCreateCommandHandler.cs
> +                    await _userAuthorizationTokenRepository.AddAsync(newToken);
Add без async

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/CreateToken/TokenCreateCommandValidator.cs
> +            if (!await _userRepository.ContainsAsync(user => user.Login == command.Login))
ContainsAsync(user => user.Login == command.Login && user.PasswordHash == command.PasswordHash)

в один можно засунуть запрос

2023-07-13 06:53 UTC, SherlockD commented on Domain/Entities/UserAuthorizationToken.cs
> +        public UserAuthorizationToken (long userId, string refreshToken,  DateTime expiryDate)
пробел

2023-07-13 06:53 UTC, SherlockD commented on Domain/Repositories/IUserAuthorizationTokenRepository.cs
> +        void Add(UserAuthorizationToken token);
у тебя вроде интерфейс для этого должен быть, IAddedRepository

2023-07-13 06:53 UTC, SherlockD commented on Domain/Repositories/IUserAuthorizationTokenRepository.cs
> +        Task<UserAuthorizationToken> GetTokenByRefreshTokenAsync(string refreshToken);
GetByRefreshTokenAsync

2023-07-13 06:53 UTC, SherlockD commented on Domain/Repositories/IUserAuthorizationTokenRepository.cs
> +        Task<UserAuthorizationToken> GetTokenByUserIdAsync(long userId);
GetByUserIdAsync

2023-07-13 06:53 UTC, SherlockD commented on Domain/Repositories/IUserAuthorizationTokenRepository.cs
> +        Task<bool> ContainsAsync(Expression<Func<UserAuthorizationToken, bool>> predicate);
тоже вынести в отдельный интерфейс, например ISearchRepository, на сколько я помню не только в этом месте используется

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/AuthenticateUser/AuthenticateUserCommand.cs
> +    public class AuthenticateUserCommand
Думаю лучше это перенести в папку Users, так как основная сущность тут пользователь

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/AuthenticateUser/AuthenticateUserCommand.cs
> +    public class AuthenticateUserCommand
В целом про эту комагду

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/AuthenticateUser/AuthenticateUserCommandHandler.cs
> +                await _userAuthorizationTokenRepository.DeleteAsync(token);
Нужно проверить, возможно DeleteAsync тоже используется если алгоритм HiLo

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/AuthenticateUser/AuthenticateUserCommandHandler.cs
> +            return new AuthorizationCommandResult<AuthenticateUserCommandDto>(authenticateUserCommandDto);
Тут тоже забыл переименовать :)

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/AuthenticateUser/AuthenticateUserCommandHandler.cs
> +            AuthenticateUserCommandDto authenticateUserCommandDto = new AuthenticateUserCommandDto
Думаю лучше по аналогии тут написать AuthenticateUserCommand**Result**

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/AuthenticateUser/AuthenticateUserCommandValidator.cs
> +            if (!await _userRepository.ContainsAsync(user => user.Login == command.Login))
Тут вроде писал, в один ContainsAsync и логин и пароль проверять и не нужно будет пользователя получать 
и все будет в одном if

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/AuthorizationCommandResult.cs
> +    public class AuthorizationCommandResult<TCommandResultData> where TCommandResultData : class
Ага, вот тут тоже просто CommandResult

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/IAuthorizationCommandHandler.cs
> +    public interface IAuthorizationCommandHandler<TResult, TCommand>
ICommandHandler

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/RefreshToken/RefreshTokenCommand.cs
> +        public DateTime RefreshTokenExpiryDate { get; init; }
В этой команде не нужен RefreshTokenExpiryDate

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/RefreshToken/RefreshTokenCommandHandler.cs
> +            string accessToken = _tokenCreator.CreateAccessToken(token.UserId);
Ага, вот этот участок кода повторяется в двух местах, получается дублирование, и это дублирование реально дублирование, если я правильно выразился) Я бы реализовал тут паттерн Factory, который на входе принимал бы UserId а все остальное заполнял сам, если есть вопросы напиши в чат

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/RefreshToken/RefreshTokenCommandHandler.cs
> +            RefreshTokenCommandDto verifyTokenCommandDto = new RefreshTokenCommandDto
Соответственно RefreshTokenCommand**Result**

2023-07-13 06:53 UTC, SherlockD commented on Application/UserAuthorizationTokens/Commands/RefreshToken/RefreshTokenCommandValidator.cs
> +            if (token.RefreshToken != command.RefreshToken)
Такого не может быть) Ты токен получаешь из репозитория, если его в репозитории нет, у тебя выше проверка сработает

2023-07-13 06:53 UTC, SherlockD commented on Infrastructure/Data/UserAuthorizationTokens/UserAuthorizationTokenConfiguration.cs
> +            builder.Property(ua => ua.RefreshToken).IsRequired();
У строковых полей лучше указывать HasMaxLength, для оптимизации

2023-07-13 06:53 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/AuthenticationController.cs
> +        public async Task<IActionResult> Registrate([FromBody] CreateUserDto createUserDto)
RegistrateUserDto, думаю если мы тут регистрируем, то комагда и все остальное должно быть связано с регистрацией

2023-07-13 06:53 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/AuthenticationController.cs
> +            _ = int.TryParse(_configuration["JWT:RefreshTokenValidityInDays"], out int tokenValidityInDay);
такого в хендлере не должно быть, из команды нужно убрать это поле, ты в бизнеслогике это можешь все получить

2023-07-13 06:53 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/AuthenticationController.cs
> +            RefreshTokenCommand verifyTokenCommand = new RefreshTokenCommand
Странно что именно эта команда используется тут, почему при аудентификации используешь RefreshTokenCommand

2023-07-13 06:53 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/AuthenticationController.cs
> +            _ = int.TryParse(_configuration["JWT:RefreshTokenValidityInDays"], out int tokenValidityInDay);
Тут тоже самое. не должен хендлер этим заниматься

2023-07-13 06:53 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/AuthenticationController.cs
> +                authenticationWithLoginDto.Map(refreshTokenExpiryDate));
Тут нужно вынести в отдельную переменную эту команду, для читабельности, не понятно во что тут маппинг происходит

2023-07-13 20:46 UTC, Nafanyan commented on Application/UserAuthorizationTokens/Commands/RefreshToken/RefreshTokenCommand.cs
> +        public DateTime RefreshTokenExpiryDate { get; init; }
RefreshTokenExpiryDate нужен чтобы записать в таблицу срок окончания действия Refresh токена.  Можно получить это значение в бизнес логике, но при таком раскладе придется тащить в бизнес логику информацию из конфигурационного файла и возвращать дату окончания действия (для добавления в куки файлы).

Я подумал, куда проще будет получить дату окончания действия Refresh токена в контроллере (на одном слое с конфигурационным файлом), здесь же использовать для создания куки и отправить в бизнес логику. 

Так получается что у меня нет никакой утечки прямой инфы от конфигурационного файла за пределы слоя с АПИ, а также useCase возвращает мне Access Token и Refresh Token, что в принципе лаконично и как мне кажется правильно.

2023-07-13 20:56 UTC, Nafanyan commented on Application/UserAuthorizationTokens/Commands/IAuthorizationCommandHandler.cs
> +    public interface IAuthorizationCommandHandler<TResult, TCommand>
Повторюсь, похоже мы всё таки не поняли друг друга:)

Первоначально согласно CQRS у меня было два интерфейса: ICommandHandler и IQueryHandler.

ICommandHandler принимает команду и возвращает только объект ValidationResult, который хранит в себе поля IsFail и Error. Команда выполняет работу с моделями, но ничего не возвращает.

IQueryHandler принимает запрос и возвращает объекты ValidationResult и Dto, которое хранит в себе информацию, которую запросил пользователь.

ICommandHandler не должно возвращать объекты, на этом была построена логика. С появление авторизации появилась нужда выполнять действия над моделями и возвращать объекты. Менять ICommandHandler не вариант, потому что на нём уже построено приложение, поэтому я создал AuthorizationCommandHandler и AuthorizationCommandResult специально для авторизации.

2023-07-18 09:30 UTC, SherlockD requested changes

2023-07-18 09:30 UTC, SherlockD commented on Domain/Entities/UserAuthorizationToken.cs
> +        public UserAuthorizationToken (long userId, string refreshToken,  DateTime expiryDate)
пробел

2023-07-18 09:30 UTC, SherlockD commented on Application/Users/Commands/AuthenticateUser/AuthenticateUserCommand.cs
> +        public DateTime NewRefreshTokenExpiryDate { get; init; }
Почему new? Просто RefreshTokenExpiryDate

2023-07-18 09:30 UTC, SherlockD commented on Application/Users/Commands/AuthenticateUser/AuthenticateUserCommand.cs
> +        public DateTime NewRefreshTokenExpiryDate { get; init; }
А почему это в команде? Разве откуда то приходит?

2023-07-18 09:30 UTC, SherlockD commented on Web/Presentation.Intranet.Api/ActionOnToken/CreateToken/TokenCreator.cs
> +        public string CreateAccessToken(long userId)
Почему в Presentation слое?

2023-07-18 09:30 UTC, SherlockD commented on Web/Presentation.Intranet.Api/ActionOnToken/DecodeToken/TokenDecoder.cs
> +namespace Presentation.Intranet.Api.ActionOnToken.DecodeToken
Это тоже почему в Presentation слое?

2023-07-18 09:30 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/AuthenticationController.cs
> +        public async Task<IActionResult> Registrate([FromBody] RegistrateUserDto registrateUserDto)
почему в этом контрелле и без привязки к сущности по rest?

2023-07-18 09:30 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/AuthenticationController.cs
> +            DateTime newRefreshTokenExpiryDate = DateTime.Now.AddDays(int.Parse(_configuration["JWT:RefreshTokenValidityInDays"]));
Илья, почему на presentation слое бизнеслогика?

2023-07-18 09:30 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Controllers/AuthenticationController.cs
> +            var s = HttpContext;
что за var s и почему нельзя сразу HttpContext юзать?

2023-07-18 09:30 UTC, SherlockD commented on Web/Presentation.Intranet.Api/TokenValidationAttribute.cs
> +    public class TokenValidationAttribute : Attribute
IAuthorizationFilter используй тут и не TokenValidationAttribute а например JwtAuthorizationAttribute

2023-07-20 06:50 UTC, SherlockD requested changes

2023-07-20 06:50 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Program.cs
> +                builder.WithOrigins("http://localhost:3000")
В конфиг можно перенести

2023-07-20 06:50 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Program.cs
> +            string connectionString = new DataBaseConfiguration().GetConnectionString("WebCalendarLocal");
Вот, о чем я говорил, ConfigurationManagement, у тебя по сути не должно быть WebCalendarLocal, WebCalendarProd, один конфиг, в зависимости от того что ты билдишь Dev или Prod подставлялись бы нужные connection string

2023-07-20 06:50 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Program.cs
> +            string connectionString = new DataBaseConfiguration().GetConnectionString("WebCalendarLocal");
Сейчас попробую найти гайд

2023-07-20 06:50 UTC, SherlockD commented on Web/Presentation.Intranet.Api/Program.cs
> +            string connectionString = new DataBaseConfiguration().GetConnectionString("WebCalendarLocal");
Вот тут об этом написано чутка, обрати внимание вот на раздел с конфигурациями в статье https://enlabsoftware.com/development/dotnet-core-environment-how-config-examples.html

2023-07-20 06:50 UTC, SherlockD commented on Web/Presentation.Intranet.Api/JwtAuthorizationAttribute.cs
> +    public class JwtAuthorizationAttribute : Attribute, IAuthorizationFilter
Думаю нужн оперенести в Infrastructure, потому что в других апишках может понадобится

2023-07-20 06:50 UTC, SherlockD commented on Web/Presentation.Intranet.Api/JwtAuthorizationAttribute.cs
> +            accessToken = accessToken.Replace("\"", "");
По принципу единственной ответственности я бы перен бизнеслогику отсюда куда то в отдельный класс в Application

2023-07-21 06:22 UTC, SherlockD approved these changes

2023-07-21 06:22 UTC, SherlockD commented on Application/Tokens/DecodeToken/TokenDecoder.cs
> +            var jsonToken = handler.ReadToken(accessToken);
var -> string

2023-07-21 06:22 UTC, SherlockD commented on Infrastructure/appsettings.Production.json
> +    "Secret": "MyVerySecretKey41 25345 4647 sd afs fdsg s agf",
Нужно норм ключ, положи сюда просто Guid, с таким ключом неудобно будет работать)

2023-07-21 06:22 UTC, SherlockD commented on Infrastructure/JwtAuthorizations/JwtAuthorizationAttribute.cs
> +            long requestId = (long)Convert.ToDouble(context.HttpContext.Request.RouteValues["userId"]);
requestUserId
tokenUserId

2023-07-21 07:58 UTC, merged