create Domain layer
Nafanyan/WebCalendar pull request #3
Opened 2023-05-02 13:45 UTC by Nafanyan

2023-05-03 06:26 UTC, SherlockD commented
Замечания #1

2023-05-05 10:43 UTC, SherlockD requested changes

2023-05-05 10:43 UTC, SherlockD commented on Domain/Events/Event.cs
> +
пробел лишний

2023-05-05 10:43 UTC, SherlockD commented on Domain/Events/Event.cs
> +        public void UpdateRecord(string record)
Наверное лучше назвать SetRecord, типа геттер сеттер, от этого оттолкнуться

2023-05-05 10:43 UTC, SherlockD commented on Domain/Events/IEventRepository.cs
> +        void Add (Event e);
посмотри реализации репозисториев в инете, там общие методы можно вынести в один репозиторий. К примеру IAddRepository, IRemoveRepository

2023-05-05 10:43 UTC, SherlockD commented on Domain/Events/IEventRepository.cs
> +        void Add (Event e);
в конкретные репозитории уже добавляешь уникальные методы, типа GetById и т д

2023-05-05 10:43 UTC, SherlockD commented on Domain/Users/User.cs
> +        public List<Event> Events { get; private set; }
Не нужна тут наверное такая жетская связь. Лучше евенты отдельно выгружить, на фронде поэкономим память и пропусную способность.

2023-05-05 10:43 UTC, SherlockD commented on Domain/Users/User.cs
> +        public List<Event> Events { get; private set; }
Просто ты пользователя будешь в бекенд запрашивать не только для того что бы список евентов вывести

2023-05-05 10:43 UTC, SherlockD commented on Domain/Users/User.cs
> +        public bool UpdatePasswordHash(string oldPasswordHash, string newPasswordHash)
думаю не стоит тут делать проверку старого пароля, это уже бизнеслогика, а не доменная модель

2023-05-05 10:43 UTC, SherlockD commented on Domain/Validation/EventValidation/ValidationEvent.cs
> +        private IEventRepository _eventRepository;
readonly

2023-05-05 10:43 UTC, SherlockD commented on Domain/Validation/EventValidation/ValidationEvent.cs
> +        public void CheckingContentInRepository(long id)
ой, зачем это в доменной модели, тут же просто модель. А тут проверки какие то, в базу залазить, не хорошо :)

2023-05-10 06:29 UTC, SherlockD requested changes

2023-05-10 06:29 UTC, SherlockD commented on Domain/Entitys/Event.cs
> +        public DateTime StartEvent { get; private set; }
Тут я бы вынес это в отдельный объект, что то типа EventPeriod, StartEvent, EndEvent в нем

2023-05-10 06:29 UTC, SherlockD commented on Domain/Entitys/Event.cs
> +        public string Record { get; private set; }
А что такое Record?)

2023-05-10 06:29 UTC, SherlockD commented on Domain/Entitys/User.cs
> +        public void UpdatePasswordHash(string oldPasswordHash, string newPasswordHash)
Зачем тут oldPasswordHash

2023-05-10 06:29 UTC, SherlockD commented on Domain/Entitys/User.cs
> +        public void UpdatePasswordHash(string oldPasswordHash, string newPasswordHash)
Замени на set по аналогии с другими entity

2023-05-10 06:29 UTC, SherlockD commented on Domain/Entitys/User.cs
> +        public void UpdateLogin(string login, string passwordHash)
Зачем тут passwordHash

2023-05-10 06:29 UTC, SherlockD commented on Domain/Repositories/IBaseRepository.cs
> +        TEntety GetById(long id);
Нельзя такое в базовый репозиторий, id может быть не long

2023-05-10 06:29 UTC, SherlockD commented on Domain/Repositories/IBaseRepository.cs
> +﻿namespace Domain.Repositories
По принципу разделения интерфейсов, лучше разделить на IAddedRepository и IRemovableRepository, потому что не во всех репозиотриях будем удалять данные, к примеру.

2023-05-10 06:29 UTC, SherlockD commented on Domain/Repositories/IBaseRepository.cs
> +        void Update(TEntety entety);
EntityFramework уже следит за изменениями объектов, тут лишний метод Update. Предлагаю воспользоваться паттерном UnitOfWork, это объект который будет коммитить изменения в базу данных. Почитай про UnitOfWork, если что то будет не понятно пиши. Если в кратце там будет только один метод commit, который будет нам обновлять бд
![image](https://github.com/Nafanyan/WebCalendar/assets/27965916/f1bdf0bd-ad9f-48d1-a88c-96560e2ef00a)

2023-05-10 06:29 UTC, SherlockD commented on Domain/Repositories/IBaseRepository.cs
> +        void Update(TEntety entety);
ИНтерфейс unitofwork должен находится в Domain

2023-05-10 06:29 UTC, SherlockD commented on Domain/Repositories/IUserRepository.cs
> +        User GetByLogin(string login);
Давай подобные функции, которые лезут напрямую в базу сделаем асинхронными, потому что это i/o

2023-05-11 04:12 UTC, Nafanyan commented on Domain/Entitys/Event.cs
> +        public string Record { get; private set; }
Запись)

2023-05-11 05:29 UTC, SherlockD requested changes

2023-05-11 05:29 UTC, SherlockD commented on Domain/Entitys/User.cs
> +        public void SetPasswordHash( string newPasswordHash)
Пожалуйста обращай внимание на форматирование, пробел лишний

2023-05-11 05:29 UTC, SherlockD commented on Domain/Repositories/BasicRepositories/IRecievedRepository.cs
> +    public interface IRecievedRepository<DbKey, TEntity>
лишний как будто интерфейс, не могу представить где бы в нашем проекте нужно было все данные получать

2023-05-11 05:29 UTC, SherlockD commented on Domain/Repositories/IEventRepository.cs
> +    public class KeysEvent
Для чего этот класс? Если он нужен, его нужно вынести в отдельный файл, для удобства. Но как будто не нужен

2023-05-11 05:29 UTC, SherlockD commented on Domain/Entitys/Event.cs
> +        public Event(string record, string description, EventPeriod eventPeriod)
Тут почему название не поменял?

2023-05-11 05:29 UTC, SherlockD commented on Domain/Entitys/Event.cs
> +    public class EventPeriod
Лучше выносить классы в отдельные файлы для удобства, если бы он был приватный и только тут использовался - ок, но его можно юзать в других местах

2023-05-11 05:30 UTC, SherlockD commented on Domain/Repositories/BasicRepositories/IRecievedRepository.cs
> +    public interface IRecievedRepository<DbKey, TEntity>
Можно в конкретных интерфейсах методы эти использовать, только там где они нужны

2023-05-11 11:50 UTC, SherlockD requested changes

2023-05-11 11:50 UTC, SherlockD commented on Domain/Entitys/EventPeriod.cs
> +﻿namespace Domain.Entitys
entities

2023-05-11 11:50 UTC, SherlockD commented on Domain/Repositories/IEventRepository.cs
> +        Task<Event> GetEvent(long keysEvent, User user);
User => userId потому что нам не нужен там весь объект

2023-05-11 11:50 UTC, SherlockD commented on Domain/Repositories/IUserRepository.cs
> +        Task<User> GetUser(long id);
GetById

2023-05-11 11:50 UTC, SherlockD commented on Domain/Repositories/IUserRepository.cs
> +        Task<IReadOnlyList<Event>> GetEvents(User user);
User => userId

2023-05-11 12:07 UTC, SherlockD requested changes

2023-05-11 12:07 UTC, SherlockD commented on Domain/Entities/EventPeriod.cs
> +                new ArgumentException("The event must occur within one day");
throw

2023-05-11 12:14 UTC, SherlockD approved these changes

2023-05-11 13:57 UTC, merged